### ISSUE TITLE
Install axios before use

### ISSUE THREAD

**Issue by ameetmadan** [inkognitro/react-app-tutorial#5]
### 8.2. 8.2 Axios request handler
```
npm install axios && npm install @types/axios --save-dev
```

**Comment by inkognitro** [comment]
Thx! FYI: Axios should come with types. No need to install @types/axios.
Fixed: https://github.com/inkognitro/react-app-tutorial/commit/2498cb056abfefad2cdf1967e8eb05693db346a9
