### ISSUE TITLE
Rename from ServiceProvider.tsx to ServiceContainer.tsx isn't clear

### ISSUE THREAD

**Issue by ameetmadan** [inkognitro/react-app-tutorial#6]
https://github.com/inkognitro/react-app-tutorial/blob/main/09-wiring.md#93-provide-the-apiv1requesthandler

File name changes from `src/ServiceProvider.tsx` to `src/ServiceContainer.tsx` and it isn't clear in which step this happened.

**Comment by inkognitro** [comment]
Fixed: [2a4ed8c1e369b30886bdf017a3b6c2bd55f5af67](https://github.com/inkognitro/react-app-tutorial/commit/2a4ed8c1e369b30886bdf017a3b6c2bd55f5af67)
