### ISSUE TITLE
New Chapter: How to Git

### ISSUE THREAD

**Issue by ameetmadan** [inkognitro/react-app-tutorial#7]
- Use [https://learngitbranching.js.org](https://learngitbranching.js.org) as the base for adding a new git chapter. 
- Add git rules to the chapter, e.g. only commit when 2 thumbs up, create branch(es) for tickets etc.

**Comment by inkognitro** [comment]
This tutorial is to broaden people's knowledge about React and its concepts, not about Git 😇
